import { OpenAPI2, OpenAPI2Schemas, OpenAPI3, OpenAPI3Schemas, SwaggerToTSOptions } from "./types";
export declare const WARNING_MESSAGE = "/**\n* This file was auto-generated by openapi-typescript.\n* Do not make direct changes to the file.\n*/\n\n\n";
export default function swaggerToTS(schema: OpenAPI2 | OpenAPI2Schemas | OpenAPI3 | OpenAPI3Schemas, options?: SwaggerToTSOptions): string;
